- hosts: all
  remote_user: ansadmin
  become: true
  tasks:
   - name: Install Docker
     when: inventory_hostname in groups['oel']
     yum:
       name: docker
       state: present
     tags:
         - Install_Docker

   - name: Stop Docker
     when: inventory_hostname in groups['oel']
     service:
         name: docker
         state: stopped
     tags:
         - Stop_Docker

   - name: Taking Backup of Docker service file with the Current date time stamp
     when: inventory_hostname in groups['oel']
     copy:
       src: /usr/lib/systemd/system/docker.service
       dest: /home/ansadmin/docker.service.{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}
       remote_src: yes
     tags:
        - Backup_Files

   - name: Copy Docker Service files from Ansible Local to remote
     when: inventory_hostname in groups['oel']
     copy:
       src: /home/ansadmin/git/docker.service
       dest: /usr/lib/systemd/system
     tags:
        - Copy_Files

   - name: Start Docker
     when: inventory_hostname in groups['oel']
     service:
         name: docker
         state: started
     tags:
         - Start_Docker

   - name: Install Podman
     when: inventory_hostname in groups['centos']
     yum:
       name: podman
       state: present
     tags:
        - Install_Podman






